name: Check Saved Docker Hub Secrets

on: [workflow_dispatch]

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check if DOCKER_USERNAME is set
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "Error: DOCKER_USERNAME is not set in secrets."
            exit 1
          else
            echo "DOCKER_USERNAME is set."
          fi

      - name: Check if DOCKER_PASSWORD is set
        run: |
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "Error: DOCKER_PASSWORD is not set in secrets."
            exit 1
          else
            echo "DOCKER_PASSWORD is set."
          fi
